### ISSUE TITLE
The filter attribute is parsed incorrectly.

### ISSUE THREAD

**Issue by skorokithakis** [clevercss/clevercss#5]
The "filter" attribute should preserve parentheses, e.g. "filter: alpha(opacity = 20)", or there should be a way to escape parentheses.

**Comment by tehfink** [comment]
i've been using this workaround, which is non-ideal:

```
('alpha(opacity=' + $banner_nav_opacity + ')').string()
```

**Comment by jaredly** [comment]
I just spent a good chunk of time merging the work that people have done for clevercss so far (it's been pretty fragmented) and reorganizing the code (it was originally a monolithig 1600+ line file!). My fork is [over here](http://github.com/jabapyth/clevercss) if you want to check it out. -- there have been several syntax additions and many added unittests.

One of these syntax additions is [backstring literals](http://github.com/jabapyth/clevercss/commit/c94d64bfb5ad872952ba0e22b76700bd1ea2dee6). With this syntax, you can embed arbitrary CSS in order to achieve whatever hacks you require. (this is especially useful for non-css2 magic, such as filter).
