### ISSUE TITLE
strings should remain intact in some cases

### ISSUE THREAD

**Issue by zahory** [clevercss/clevercss#9]
clevercss should not eat quotes in:
    .clearfix:after:
        content: "."
or there should be way to escape quotes.
This is a showstopper. Or am I missing something?

**Comment by tehfink** [comment]
see workaround:
http://github.com/dziegler/clevercss/issues/#issue/5/comment/186268

**Comment by jaredly** [comment]
I just spent a good chunk of time merging the work that people have done for clevercss so far (it's been pretty fragmented) and reorganizing the code (it was originally a monolithig 1600+ line file!). My fork is over here if you want to check it out. -- there have been several syntax additions and many added unittests.

One of these syntax additions is [backstring literals](http://github.com/jabapyth/clevercss/commit/c94d64bfb5ad872952ba0e22b76700bd1ea2dee6). With this syntax, you can embed arbitrary CSS in order to achieve whatever hacks you require. (this is especially useful for non-css2 magic, such as filter).
